/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import frontend.FrmBuku;
import frontend.FrmKategori;
import frontend.FrmPeminjaman;

/**
 *
 * @author hp
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        mFrmKategori = new javax.swing.JMenuItem();
        mFrmAnggota = new javax.swing.JMenuItem();
        mFrmBuku = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuMaster.setText("Pengisian Data");

        mFrmKategori.setText("Form Kategori");
        mFrmKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmKategoriActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmKategori);

        mFrmAnggota.setText("Form Anggota");
        mFrmAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmAnggotaActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmAnggota);

        mFrmBuku.setText("Form Buku");
        mFrmBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFrmBukuActionPerformed(evt);
            }
        });
        menuMaster.add(mFrmBuku);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi Peminjaman");

        jMenuItem4.setText("Form Peminjaman");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuTransaksi.add(jMenuItem4);

        jMenuBar1.add(menuTransaksi);

        menuLogOut.setText("Log Out");
        jMenuBar1.add(menuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mFrmKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmKategoriActionPerformed
       FrmKategori frmKategori = new FrmKategori();
       frmKategori.setVisible(true);
    }//GEN-LAST:event_mFrmKategoriActionPerformed

    private void mFrmAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmAnggotaActionPerformed
       FrmAnggota formAnggota = new FrmAnggota();
       formAnggota.setVisible(true);
    }//GEN-LAST:event_mFrmAnggotaActionPerformed

    private void mFrmBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFrmBukuActionPerformed
        FrmBuku frmBuku = new FrmBuku();
        frmBuku.setVisible(true);
    }//GEN-LAST:event_mFrmBukuActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmPeminjaman frmPeminjaman = new FrmPeminjaman();
        frmPeminjaman.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem mFrmAnggota;
    private javax.swing.JMenuItem mFrmBuku;
    private javax.swing.JMenuItem mFrmKategori;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
